language: ruby
install:
- bundle install
script:
- bundle exec jekyll build
cache: 
- bundler
sudo: false # route build to the container-based infrastructure for a faster build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  kepp-history: true
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: master